// Desc: Data for the app

var countries = [
  { value: "", text: "" },
  { text: "Austria", value: "Austria", selected: false },
  { text: "Belgium", value: "Belgium", selected: false },
  { text: "Bulgaria", value: "Bulgaria", selected: false },
  { text: "Belarus", value: "Belarus", selected: false },
  { text: "Croatia", value: "Croatia", selected: false },
  { text: "Cyprus", value: "Cyprus", selected: false },
  { text: "Czech Republic", value: "Czech Republic", selected: false },
  { text: "Denmark", value: "Denmark", selected: false },
  { text: "Estonia", value: "Estonia", selected: false },
  { text: "Finland", value: "Finland", selected: false },
  { text: "France", value: "France", selected: false },
  { text: "Germany", value: "Germany", selected: false },
  { text: "Gibraltar", value: "Gibraltar", selected: false },
  { text: "Greece", value: "Greece", selected: false },
  { text: "Guernsey", value: "Guernsey", selected: false },
  { text: "Hungary", value: "Hungary", selected: false },
  { text: "Iceland", value: "Iceland", selected: false },
  { text: "Ireland", value: "Ireland", selected: false },
  { text: "Isle of Man", value: "Isle of Man", selected: false },
  { text: "Italy", value: "Italy", selected: false },
  { text: "Jersey", value: "Jersey", selected: false },
  { text: "Kosovo", value: "Kosovo", selected: false },
  { text: "Latvia", value: "Latvia", selected: false },
  { text: "Liechtenstein", value: "Liechtenstein", selected: false },
  { text: "Lithuania", value: "Lithuania", selected: false },
  { text: "Luxembourg", value: "Luxembourg", selected: false },
  { text: "Malta", value: "MaltaT", selected: false },
  { text: "Moldova, Republic of", value: "Moldova, Republic of", selected: false },
  { text: "Monaco", value: "Monaco", selected: false },
  { text: "Montenegro", value: "Montenegro", selected: false },
  { text: "Netherlands", value: "Netherlands", selected: false },
  { text: "North Macedonia", value: "North Macedonia", selected: false },
  { text: "Norway", value: "Norway", selected: false },
  { text: "Poland", value: "Poland", selected: false },
  { text: "Portugal", value: "Portugal", selected: false },
  { text: "Romania", value: "Romania", selected: false },
  { text: "Russian Federation", value: "Russian Federation", selected: false },
  { text: "San Marino", value: "San Marino", selected: false },
  { text: "Serbia", value: "Serbia", selected: false },
  { text: "Slovakia", value: "Slovakia", selected: false },
  { text: "Slovenia", value: "Slovenia", selected: false },
  { text: "Spain", value: "Spain", selected: false },
  { text: "Svalbard and Jan Mayen Islands", value: "Svalbard and Jan Mayen Islands", selected: false },
  { text: "Sweden", value: "Sweden", selected: false },
  { text: "Switzerland", value: "Switzerland", selected: false },
  { text: "Ukraine", value: "Ukraine", selected: false },
  { text: "United Kingdom", value: "United Kingdom", selected: false },
  { text: "United Kingdom (Northern Ireland)", value: "United Kingdom (Northern Ireland)", selected: false },
  { text: "Vatican City", value: "Vatican City", selected: false },
];

// Desc: Data for the app

var nationalities = [
  { value: "", text: "" },
  { text: "Austrian", value: "Austrian", selected: false },
  { text: "Belgian", value: "Belgian", selected: false },
  { text: "Bulgarian", value: "Bulgarian", selected: false },
  { text: "Belarusian", value: "Belarusian", selected: false },
  { text: "British", value: "British", selected: false },
  { text: "Croatian", value: "Croatian", selected: false },
  { text: "Cypriot", value: "Cypriot", selected: false },
  { text: "Czech", value: "Czech", selected: false },
  { text: "Danish", value: "Danish", selected: false },
  { text: "Estonian", value: "Estonian", selected: false },
  { text: "Finnish", value: "Finnish", selected: false },
  { text: "French", value: "French", selected: false },
  { text: "German", value: "German", selected: false },
  { text: "Greek", value: "Greek", selected: false },
  { text: "Hungarian", value: "Hungarian", selected: false },
  { text: "Icelander", value: "Icelander", selected: false },
  { text: "Irish", value: "Irish", selected: false },
  { text: "Italian", value: "Italian", selected: false },
  { text: "Kosovar", value: "Kosovar", selected: false },
  { text: "Latvian", value: "Latvian", selected: false },
  { text: "Lithuanian", value: "Lithuanian", selected: false },
  { text: "Luxembourger", value: "Luxembourger", selected: false },
  { text: "Maltese", value: "Maltese", selected: false },
  { text: "Moldovan", value: "Moldovan", selected: false },
  { text: "Dutch", value: "Dutch", selected: false },
  { text: "North Macedonian", value: "North Macedonian", selected: false },
  { text: "Norwegian", value: "Norwegian", selected: false },
  { text: "Polish", value: "Polish", selected: false },
  { text: "Portuguese", value: "Portuguese", selected: false },
  { text: "Romanian", value: "Romanian", selected: false },
  { text: "Russian", value: "Russian", selected: false },
  { text: "San Marino", value: "San Marino", selected: false },
  { text: "Serbia", value: "Serbia", selected: false },
  { text: "Slovakia", value: "Slovakia", selected: false },
  { text: "Slovenia", value: "Slovenia", selected: false },
  { text: "Spanish", value: "Spanish", selected: false },
  { text: "Swedish", value: "Swedish", selected: false },
  { text: "Swiss", value: "Swiss", selected: false },
  { text: "Ukrainian", value: "Ukrainian", selected: false },
];

// exports
module.exports = {
  countries,
  nationalities

}
